// Validation diagnostics are optimistic by default. Each rule turns its own
// diagnostic flag to false when it detects an invalid diagram condition.
export const DEFAULT_DIAGNOSTICS = {
    noRepeatedNames: true,
    noRepeatedAttrNames: true,
    noEmptyCompositeAttributes: true,
    noNestedCompositeAttributes: true,
    noUnsupportedMultivaluedAttributes: true,
    noEntitiesWithoutAttributes: true,
    noEntitiesWithoutPK: true,
    noEntitiesWithMoreThanOnePK: true,
    noNMRelationsWithPK: true,
    noUnconnectedRelations: true,
    noAttributesInNonNMRelations: true,
    noBrokenRelationEntityReferences: true,
    noUnconnectedIsas: true,
    noBrokenIsaEntityReferences: true,
    noIsaHierarchiesWithRepeatedSpecializations: true,
    noIsaHierarchiesWithGeneralizationAsSpecialization: true,
    noIsaSpecializationsInMultipleHierarchies: true,
    noIsaSpecializationsWithPrimaryKey: true,
    noTernaryRelationsWithAmbiguousRepeatedParticipants: true,
    noIdentifyingTernaryRelations: true,
    noTernaryRelationsWithMandatoryCardinalities: true,
    noNotValidCardinalities: true,
    noSQLIdentifierCollisions: true,
    noWeakEntitiesWithoutPartialKey: true,
    noWeakEntitiesWithMoreThanOnePartialKey: true,
    noWeakEntitiesWithPrimaryKey: true,
    noStrongEntitiesWithPartialKey: true,
    noWeakEntitiesWithoutIdentifyingRelation: true,
    noInvalidIdentifyingRelations: true,
    noInvalidIdentifyingCardinalities: true,
    noInconsistentWeakEntityOwnership: true,
    noMultipleIdentifyingRelationsPerWeakEntity: true,
    notEmpty: true,
    isValid: true,
};
